### ISSUE TITLE
Different date format not matching

### ISSUE THREAD

**Issue by otavio-s-s** [pcsingh/WhatsApp-Chat-Analyzer#3]
There's a problem in reading other date formats. In English Whatsapp, there's a comma between date and time. Like this:

![Screen-Shot-2017-11-03-at-11.42.08.jpg](https://www.imagemhost.com.br/images/2020/08/01/Screen-Shot-2017-11-03-at-11.42.08.jpg)

There's no such comma in Portuguese Whatsapp:

![Capturar.png](https://www.imagemhost.com.br/images/2020/08/01/Capturar.png)

Without the comma, the date does not match the regex pattern. Look at the outputs:

![Capturar1.png](https://www.imagemhost.com.br/images/2020/08/01/Capturar1.png)
![Capturar2.png](https://www.imagemhost.com.br/images/2020/08/01/Capturar2.png)

If you're interested in fixing it, I've created a pull request.

**Comment by otavio-s-s** [comment]
Hello @pcsingh!

There's another issue regarding dates. I do not think it's necessary to open issue as this one is already about date formats.

Brazilian standard date format is dd/mm/yyyy and not mm/dd/yyyy. So, although the app works fine with Brazillian WhatsApp text files, the dates are displayed completely wrong.

My suggestion is to set a different date format in the same `if` where the app checks for the comma. The `getDataPoint` function would then return date, time, author, message, and date_format. `date_format` would be either `'%d/%m/%Y` or `'%m/%m/%Y'` and would be passed to the `pd.to_datetime` function to properly convert the dates.

Another approach would be to ask the user to inform the date format, but I think the first one is better. 

What do you think?

**Comment by pcsingh** [comment]
Can you share the screenshots?

**Comment by otavio-s-s** [comment]
Sure!

The .txt file:

![Capturar3](https://user-images.githubusercontent.com/60897189/89420113-a4a1d180-d708-11ea-8e75-bc64df2de818.PNG)

The current app:

![Capturar](https://user-images.githubusercontent.com/60897189/89420094-a10e4a80-d708-11ea-80c3-9db688b9d288.PNG)

App with the modifications I suggested:

![Capturar2](https://user-images.githubusercontent.com/60897189/89420073-99e73c80-d708-11ea-9ee7-bd59d1d57fbd.PNG)

**Comment by pcsingh** [comment]
Go ahead 👍
