### ISSUE TITLE
Error when load the file

### ISSUE THREAD

**Issue by yancyrafael** [pcsingh/WhatsApp-Chat-Analyzer#8]
Hello 

I'm testing the application when I upload the file I have this error:

Please upload the WhatsApp chat dataset!

**Comment by pcsingh** [comment]
Hi @yancyrafael,

Please, use the attached dummy_chat_file to check its working and select the date format as `dd/mm/yy`.

[dummy_chat_file.txt](https://github.com/pcsingh/WhatsApp-Chat-Analyzer/files/5899208/dummy_chat_file.txt)

**Comment by yancyrafael** [comment]
I test it and works 

my data date format is:

[4/3/20 11:01:50]

What could be wrong?

**Comment by pcsingh** [comment]
Nothing wrong with it, every country has a different format of chats. I and @otavio-s-s try to handle some formats, and that's the reason we have given the option to choose `date format`.

Upload the file, choose the correct date format (mm/dd/yy I think for the given format) and it will show the plots. You can see the `custom_modules\func_use_extract_data.py` file where we are cleaning and transforming the chat file into a dataframe.

**Comment by yancyrafael** [comment]
Hello 
your chat test works, but mine doesn't even I put the correct date_format for example:
[11/12/20 12:33:47]
I select dd/mm/yy 

Still have the error: Please upload the WhatsApp chat dataset!

WIth your chat example works fine,

**Comment by pcsingh** [comment]
Is it possible that you can share the `dummy_chat` file for the chat you are trying to upload in the same format?

So that I can look at it and find the problem.

**Comment by yancyrafael** [comment]
[test.txt](https://github.com/pcsingh/WhatsApp-Chat-Analyzer/files/5911675/test.txt)
Please review part of the file

**Comment by pcsingh** [comment]
Chat format, I used at the time of formating

![image](https://user-images.githubusercontent.com/44555033/106757343-38237300-6656-11eb-898d-e1ca51474775.png)
You can see that it contain a `-` sign between the DateTime and message.

Your chat format

![image](https://user-images.githubusercontent.com/44555033/106757513-70c34c80-6656-11eb-95e7-f174086f14a7.png)
It does not contain any `-` sign between DateTime and the message.

And I used the `-` sign to separate the message and the DateTime part. In the code [here](https://github.com/pcsingh/WhatsApp-Chat-Analyzer/blob/master/custom_modules/func_use_extract_data.py#L45).

![image](https://user-images.githubusercontent.com/44555033/106758110-22fb1400-6657-11eb-9f83-75e4ad995889.png)

You can make a contribution by solving this issue. So that it can handle both the WhatsApp chat format.

**Comment by pcsingh** [comment]
Hey @yancyrafael,

I have shared the notebook which contains functions for the formating of chat into a pandas dataframe. Use it and try to debug and find the problem.

Start from cells 7 give the location of the chat file to the variable `filename` and start moving towards the functions step by step.

I would suggest first use the dummy_chat_file.txt and see how things are working. Then use your chat file and find the problem.

I hope that will help you.

[dummy_chat_file.txt](https://github.com/pcsingh/WhatsApp-Chat-Analyzer/files/5919295/dummy_chat_file.txt)

Follow this [link](https://drive.google.com/file/d/1oW3Y-ppnLFlOLdJRASPeffoRaj1-VcAh/view?usp=sharing) to download the *notebook.ipynb* file. Let me know when you are done with the download.

**Comment by yancyrafael** [comment]
I made some changes please review. 
[chat_1234.txt](https://github.com/pcsingh/WhatsApp-Chat-Analyzer/files/5962681/chat_1234.txt)
[https://drive.google.com/file/d/18Cmz31By_mHZKBxXy1qW-qYWklQCajxY/view?usp=sharing](url)

**Comment by pcsingh** [comment]
> [https://drive.google.com/file/d/18Cmz31By_mHZKBxXy1qW-qYWklQCajxY/view?usp=sharing](url)

Hey, @yancyrafael 
I think this link is not working, I am not able to access the file.

**Comment by pcsingh** [comment]
If you are comfortable that the changes can also handle your chat format without disturbing the working of app. Find the functions in the main application file, make changes and run in your local system. 

When you feel that its working, feel free to push your changes.  Happy coding!

**Comment by Vermana315** [comment]
i tried but its givig erroe me too on dummy  chat file

**Comment by himanshu1315sharma** [comment]
the error is Something is wrong in loading the data! Please select the correct date format or Try again. Error Type: UserHashError
even after using dummy dataset and the date format you prescribed

**Comment by pcsingh** [comment]
@himanshu1315sharma you can take the fresh code and use the dummy_chat directory file for it. Also, you can see the live project [here](https://whatsapp-chat-analyzer-4i8l.onrender.com/).

**Comment by pcsingh** [comment]
Updated the project code you can now explore it. I don't think there is any error in loading the file. That's why closing this issue.
